FROM golang:1.16
WORKDIR /app
COPY . .
WORKDIR /app/cmd/devices
RUN go mod tidy
WORKDIR /app
RUN CGO_ENABLED=0 go build -o devices ./cmd/devices/main.go

FROM alpine:3.14
COPY --from=0 /app/devices /
COPY ./est-config.json /app/clientcas.json
CMD ["/devices"]
