FROM golang:1.16
WORKDIR /app
COPY . .
WORKDIR /app/cmd
ENV GOSUMDB=off
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o devices ./main.go

FROM alpine:3.14
COPY --from=0 /app/cmd/devices /
COPY ./docs/swagger.json /docs/swagger.json
COPY ./est-config.json /app/clientcas.json
CMD ["/devices"]
